# Generated by Django 3.1 on 2020-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapath',
            name='detforecastprefix',
            field=models.CharField(default='value', max_length=255),
        ),
        migrations.AddField(
            model_name='datapath',
            name='ensforecastprefix',
            field=models.CharField(default='value', max_length=255),
        ),
    ]
