# Generated by Django 3.1 on 2020-08-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_viewer', '0002_auto_20200821_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapath',
            name='detforecastprefix',
            field=models.CharField(default='hkhControl_', max_length=255),
        ),
        migrations.AlterField(
            model_name='datapath',
            name='directory',
            field=models.TextField(default='/mnt/hiwat/hkh/image_files'),
        ),
        migrations.AlterField(
            model_name='datapath',
            name='ensforecastprefix',
            field=models.CharField(default='hkhEnsemble_', max_length=255),
        ),
    ]
