# Generated by Django 4.1.7 on 2024-01-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_viewer', '0003_auto_20200826_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
