# Generated by Django 4.1.7 on 2024-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_viewer', '0005_domain_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='det_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='ens_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
